#!/bin/sh

TESTER="tester"

OUT_PATH=`pwd`/out

echo $OUT_PATH
if [ ! -e $OUT_PATH ]; then
  mkdir -p $OUT_PATH
fi

echo "preparing test...";
make
clear
chmod +x ${TESTER}
./${TESTER} __tx_nrb__ft $@
make clean
rm -rf $OUT_PATH